In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("twcs.csv")

In [4]:
df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [5]:
df.shape

(2811774, 7)

In [6]:
df.columns

Index(['tweet_id', 'author_id', 'inbound', 'created_at', 'text',
       'response_tweet_id', 'in_response_to_tweet_id'],
      dtype='str')

In [7]:
company_tweets = df[df["inbound"] == False]

company_tweets["author_id"].value_counts().head(20)

author_id
AmazonHelp         169840
AppleSupport       106860
Uber_Support        56270
SpotifyCares        43265
Delta               42253
Tesco               38573
AmericanAir         36764
TMobileHelp         34317
comcastcares        33031
British_Airways     29361
SouthwestAir        28977
VirginTrains        27817
Ask_Spectrum        25860
XboxSupport         24557
sprintcare          22381
hulu_support        21872
sainsburys          19466
GWRHelp             19364
AskPlayStation      19098
ChipotleTweets      18749
Name: count, dtype: int64

In [8]:
amazon_df = df[df["author_id"] == "AmazonHelp"].copy()

amazon_df.shape

(169840, 7)

In [9]:
amazon_df["inbound"].value_counts()

inbound
False    169840
Name: count, dtype: int64

In [10]:
amazon_responses = amazon_df[
    amazon_df["in_response_to_tweet_id"].notna()
].copy()

amazon_responses.shape

(169287, 7)

In [11]:
amazon_responses["in_response_to_tweet_id"].head(10)

181    272.0
184    271.0
186    274.0
234    325.0
321    617.0
323    616.0
326    621.0
328    624.0
330    623.0
332    628.0
Name: in_response_to_tweet_id, dtype: float64

In [12]:
parent_ids = amazon_responses["in_response_to_tweet_id"].head(10).astype(int)

df[df["tweet_id"].isin(parent_ids)][
    ["tweet_id", "author_id", "inbound", "text"]
]

,tweet_id,author_id,inbound,text
183,271,115770,True,@AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎ...
185,274,115770,True,@AmazonHelp こちらこそありがとうございました。
187,272,115770,True,amazonのfireTVstickが見れない😢
235,325,115792,True,amazonプライムビデオ、再生エラーが多いです
322,616,115820,True,@AmazonHelp 3 different people have given 3 di...
325,617,115820,True,Way to drop the ball on customer service @1158...
327,621,115822,True,@115823 I want my amazon payments account CLOS...
329,623,115824,True,"@AmazonHelp Okay, danke für die Info"
331,624,115824,True,"@115825 also, beim Addams Family-Film in Prime..."
335,628,115826,True,@115828 How about you guys figure out my Xbox ...

In [13]:
amazon_pairs = amazon_responses.merge(
    df[["tweet_id", "text"]],
    left_on="in_response_to_tweet_id",
    right_on="tweet_id",
    suffixes=("_response", "_customer")
)

amazon_pairs.shape

(168823, 9)

In [14]:
amazon_pairs.head(10)

,tweet_id_response,author_id,inbound,created_at,text_response,response_tweet_id,in_response_to_tweet_id,tweet_id_customer,text_customer
0,269,AmazonHelp,False,Wed Nov 22 09:23:01 +0000 2017,@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは...,"270,271",272.0,272,amazonのfireTVstickが見れない😢
1,273,AmazonHelp,False,Wed Nov 22 09:40:27 +0000 2017,@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました...,274,271.0,271,@AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎ...
2,275,AmazonHelp,False,Wed Nov 22 10:06:26 +0000 2017,@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお...,NaN,274.0,274,@AmazonHelp こちらこそありがとうございました。
3,324,AmazonHelp,False,Wed Nov 22 09:06:00 +0000 2017,@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の...,NaN,325.0,325,amazonプライムビデオ、再生エラーが多いです
4,615,AmazonHelp,False,Tue Oct 31 22:29:00 +0000 2017,@115820 I'm sorry we've let you down! Without ...,616,617.0,617,Way to drop the ball on customer service @1158...
5,618,AmazonHelp,False,Tue Oct 31 23:28:00 +0000 2017,@115820 We'd like to take a further look into ...,619,616.0,616,@AmazonHelp 3 different people have given 3 di...
6,620,AmazonHelp,False,Tue Oct 31 22:28:34 +0000 2017,@115822 I am unable to affect your account via...,NaN,621.0,621,@115823 I want my amazon payments account CLOS...
7,622,AmazonHelp,False,Tue Oct 31 22:28:00 +0000 2017,"@115824 Hi, wir erhalten die Filme/Serien so v...",623,624.0,624,"@115825 also, beim Addams Family-Film in Prime..."
8,625,AmazonHelp,False,Tue Oct 31 22:34:32 +0000 2017,@115824 Wir haben zu danken. Schönen Abend noc...,NaN,623.0,623,"@AmazonHelp Okay, danke für die Info"
9,626,AmazonHelp,False,Tue Oct 31 22:28:00 +0000 2017,@115826 I'm sorry for the wait. You'll receive...,627,628.0,628,@115828 How about you guys figure out my Xbox ...

In [15]:
amazon_pairs[[
    "text_customer",
    "text_response"
]].head(10)

,text_customer,text_response
0,amazonのfireTVstickが見れない😢,@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは...
1,@AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎ...,@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました...
2,@AmazonHelp こちらこそありがとうございました。,@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお...
3,amazonプライムビデオ、再生エラーが多いです,@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の...
4,Way to drop the ball on customer service @1158...,@115820 I'm sorry we've let you down! Without ...
5,@AmazonHelp 3 different people have given 3 di...,@115820 We'd like to take a further look into ...
6,@115823 I want my amazon payments account CLOS...,@115822 I am unable to affect your account via...
7,"@115825 also, beim Addams Family-Film in Prime...","@115824 Hi, wir erhalten die Filme/Serien so v..."
8,"@AmazonHelp Okay, danke für die Info",@115824 Wir haben zu danken. Schönen Abend noc...
9,@115828 How about you guys figure out my Xbox ...,@115826 I'm sorry for the wait. You'll receive...

In [16]:
amazon_pairs["tweet_id_customer"].nunique()

154985

In [17]:
amazon_pairs["tweet_id_customer"].value_counts().describe()

count    154985.000000
mean          1.089286
std           0.320203
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           6.000000
Name: count, dtype: float64

In [18]:
amazon_pairs["tweet_id_customer"].value_counts().value_counts().sort_index()

count
1    142709
2     10785
3      1429
4        55
5         5
6         2
Name: count, dtype: int64

In [19]:
amazon_pairs[["tweet_id_customer", "tweet_id_response"]].duplicated().sum()

np.int64(0)

In [20]:
amazon_pairs[["text_customer", "text_response"]].isna().sum()

text_customer    0
text_response    0
dtype: int64

In [21]:
amazon_pairs["customer_length"] = amazon_pairs["text_customer"].str.len()
amazon_pairs["response_length"] = amazon_pairs["text_response"].str.len()

amazon_pairs[["customer_length", "response_length"]].describe()

       customer_length  response_length
count    168823.000000    168823.000000
mean        116.588936       123.936845
std          59.100368        46.186706
min           7.000000         7.000000
25%          72.000000        98.000000
50%         118.000000       123.000000
75%         145.000000       135.000000
max         365.000000       305.000000

In [22]:
amazon_pairs.sort_values("customer_length")[[
    "text_customer",
    "text_response"
]].head(20)

       text_customer                                      text_response
154640       @115850             @773651 Hello, how may I help you? ^NS
92415        @115821  @442253 Sorry to know that the product is defe...
155595       @115850  @777178 I'm sorry but we were unable to appreh...
33688        @120533  @219052 Bonjour , que pourrais-je faire pour v...
854          @118919         @120265 Hi, how can we help you today? ^HK
66485        @119625  @350250 Hello, are you looking for any assista...
156446       @115825           @781498 Ja? Was gibt es? Lieben Gruß ^NW
55381        @115850  @206099 Allow our support team to look into th...
160844       @115821  @797324 Amazon does not offer sale adjustments...
135588       @115850  @689154 Is there anything we may assist you wi...
152771       @116875   @765126 Hola Teufel, ¿cómo podemos ayudarte? ^DA
134114       @116090  @684978 Hey! Thanks for reaching out! We won't...
144293       @115850                       @725323 How may we help? ^JS
112558       @115850  @524862 Looks like you have a question, Ashok....
120280       @115850  @618728 Hello Ajeez, How have you been? What r...
160487      Ａｍａｚｏｎ便利  @795715 嬉しいお言葉、ありがとうございます！！\n今後ともAmazonをどうぞよろし...
74381       アマゾン届かない  @379515 アマゾンです。注文履歴に記載の予定日を過ぎている場合、発送元をご確認の上、そ...
100177     アマゾン妙に重いな  @470441 ご不便おかけしております。Amazonのサイトがつながりにくい状況でしょうか...
163755     @116875 R  @805452 Hola adda. ¿Aprovechaste nuestras ofer...
126520     Amazonエラー  @658251 ご迷惑をおかけしております。現在も問題が解決されておりませんでしょうか？\n...

In [23]:
amazon_pairs["text_customer"].str.contains(
    r"[^\x00-\x7F]",
    regex=True
).mean()

np.float64(0.31801946417253574)

In [24]:
amazon_pairs["text_customer"].str.strip().eq("").sum(), amazon_pairs["text_response"].str.strip().eq("").sum()

(np.int64(0), np.int64(0))

In [25]:
amazon_pairs[["text_customer", "text_response"]].sample(20, random_state=42)

,text_customer,text_response
117216,Yo necesitaba elevar el espejo de mi tocador y...,"@565800 Hola, Aranzazu. ¡Una solución intelige..."
119196,@AmazonHelp Once You Receive..? I did't Send b...,@367525 Sorry for the confusion. Request you t...
107470,@AmazonHelp so I’ve had an issue and no one ha...,@479947 We'd love to take a closer look into y...
71350,@AmazonHelp Thank you,"@366678 You are welcome, Akshay. ^AU"
34854,@137605 Ayer no me entregaron un paquete de @1...,"@221198 Hola, lamentamos los inconvenientes qu..."
153061,@AmazonHelp please help me understand why I am...,@602543 I'm very sorry for any difficulties. W...
95196,"@AmazonHelp Just track order, return or replac...",@451690 The seller is in the best position to ...
75565,@AmazonHelp - Order No 407-6706063-7981118. Go...,@383173 Please don’t provide your order detail...
21049,@AmazonHelp That takes me to the .com site. I ...,@187800 That link will send your info to our S...
159330,fiz comprinhas na amazon quinta e já recebi. @...,"@791495 Olá Analua! Que emoção!😱 Me diga, que..."
82781,Amazonから自分宛に届いた商品が見覚えのないもので納品書も入ってないらしいし、でも電話番...,@410361 お知り合いの方からの贈り物の場合もございますが、お心当たりがない場合にはお手...
54774,@AmazonHelp Haven't got any details. It would ...,@306432 Kindly wait till you receive an update...
31038,@AmazonHelp @AmazonHelp please refer to the fi...,@214626 We cannot view your account details vi...
121398,huh guess i have amazon prime now,@625773 Hmm... Well do you want some informati...
57556,@AmazonHelp Only winners ? and what is the dat...,@191566 Please click here: https://t.co/Sb5MX1...
46974,Nooo @115821 how could you let me down by not ...,@272879 Oh no! Have we missed a delivery date ...
44106,@115821 @AmazonHelp If the delivery date was n...,@239953 Sorry to hear this Kevin. Have you che...
70816,@AmazonHelp Order no. 406-6787527-3269912 date...,@364452 Please don't provide your order detail...
28890,@AmazonHelp Yep it set as default in the app. ...,@207240 Hmm. Let's take a closer look here: ht...
167758,結構な数の名作映画が見放題なの、控えめに言ってAmazon prime video神じゃない...,@819099 |ω・)ﾁﾗｯ\n存分にお楽しみください！( *• ̀ω•́ )b✨ YM

In [26]:
amazon_pairs["text_customer"].duplicated().sum()

np.int64(15810)

In [27]:
amazon_pairs[
    amazon_pairs["tweet_id_customer"].duplicated(keep=False)
][
    ["tweet_id_customer", "text_customer", "tweet_id_response", "text_response"]
].sort_values("tweet_id_customer").head(20)

,tweet_id_customer,text_customer,tweet_id_response,text_response
31,686,@AmazonHelp Already contacted 3-4 times in the...,684,@115849 Please share your details here:https:/...
69053,686,@AmazonHelp Already contacted 3-4 times in the...,688,"@115849 I understand your concern, James. Allo..."
33,690,@115850 @115821 @AmazonHelp @115851 Order# 363...,689,@115849 Please report this to our support team...
168715,690,@115850 @115821 @AmazonHelp @115851 Order# 363...,691,@115849 Apologies for the delay in delivery of...
59,1748,@AmazonHelp that is not my apartment!!!!!!! Th...,1749,@116094 I'm so sorry! We'd like to make sure t...
58,1748,@AmazonHelp that is not my apartment!!!!!!! Th...,1747,"@116094 (2/2) Also, for your security, I'd rec..."
686,2561,Erm @AmazonHelp I bought this item for £5.99.....,2562,@116318 I'm sorry you didn't receive the refun...
74,2561,Erm @AmazonHelp I bought this item for £5.99.....,2560,@116318 We'd like to take a closer look into ...
89,3655,just noticed I paid £4.95 delivery on Amazon s...,3654,"@116586 Hi, you can edit your order at any tim..."
34534,3655,just noticed I paid £4.95 delivery on Amazon s...,3656,@116586 Sorry to hear this. Did you select Fre...
105,3753,"@AmazonHelp Mac book pro, with Chrome",3755,@116617 Hi! I just wanted to ask if my colleag...
104,3753,"@AmazonHelp Mac book pro, with Chrome",3754,@116617 In this case please contact my colleag...
158571,5249,@115850 Amazon Order Id: 406-7312247-1577105...,2832866,@788662 Apologies for the delay with the deliv...
158565,5249,@115850 Amazon Order Id: 406-7312247-1577105...,2832865,@788662 Please don't share your order details ...
161407,5265,@115850 I have ordered on 24 and still you are...,2878711,@798989 Sorry for the delay in delivering the ...
161408,5265,@115850 I have ordered on 24 and still you are...,2878712,@798989 Please don't provide your order detail...
150565,5304,I have 2 echos and set up multi room music pla...,5305,@116931 We can help take a closer look into th...
161,5304,I have 2 echos and set up multi room music pla...,5303,@116931 Please try asking Alexa to stop playin...
175,5786,【新 一日一句】10.31\n\nハロウィンは\nクレームさえも\n吹き飛ばす🎃\n\nA...,5785,@117087 ご迷惑をおかけしております。お届けした商品に問題があった場合、Amazonが...
117322,5786,【新 一日一句】10.31\n\nハロウィンは\nクレームさえも\n吹き飛ばす🎃\n\nA...,5787,@117087 なお、マーケットプレイスの出品者が発送する商品の場合には、出品者毎にポリシー...

In [28]:
amazon_pairs.dtypes

tweet_id_response            int64
author_id                      str
inbound                       bool
created_at                     str
text_response                  str
response_tweet_id              str
in_response_to_tweet_id    float64
tweet_id_customer            int64
text_customer                  str
customer_length              int64
response_length              int64
dtype: object

In [29]:
amazon_pairs["created_at"].head(10)

0    Wed Nov 22 09:23:01 +0000 2017
1    Wed Nov 22 09:40:27 +0000 2017
2    Wed Nov 22 10:06:26 +0000 2017
3    Wed Nov 22 09:06:00 +0000 2017
4    Tue Oct 31 22:29:00 +0000 2017
5    Tue Oct 31 23:28:00 +0000 2017
6    Tue Oct 31 22:28:34 +0000 2017
7    Tue Oct 31 22:28:00 +0000 2017
8    Tue Oct 31 22:34:32 +0000 2017
9    Tue Oct 31 22:28:00 +0000 2017
Name: created_at, dtype: str

In [30]:
pd.to_datetime(amazon_pairs["created_at"], errors="coerce").isna().sum()

C:\Users\Asus\AppData\Local\Temp\ipykernel_2256\1378784826.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(amazon_pairs["created_at"], errors="coerce").isna().sum()

np.int64(0)

In [31]:
amazon_pairs["text_customer"].str.len().describe()

count    168823.000000
mean        116.588936
std          59.100368
min           7.000000
25%          72.000000
50%         118.000000
75%         145.000000
max         365.000000
Name: text_customer, dtype: float64

In [32]:
amazon_pairs["text_response"].str.len().describe()

count    168823.000000
mean        123.936845
std          46.186706
min           7.000000
25%          98.000000
50%         123.000000
75%         135.000000
max         305.000000
Name: text_response, dtype: float64

In [33]:
amazon_pairs["text_customer"].str.len().value_counts().sort_index().head(20)

text_customer
7      15
8       2
9      11
10     21
11     37
12     30
13     54
14    190
15    384
16    466
17    336
18    338
19    511
20    324
21    503
22    521
23    525
24    501
25    506
26    476
Name: count, dtype: int64

In [34]:
amazon_pairs["text_customer"].nunique()

153013

In [35]:
amazon_pairs.groupby("text_customer")["text_response"].nunique().describe()

count    153013.000000
mean          1.103325
std           0.688490
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max         129.000000
Name: text_response, dtype: float64

In [36]:
pd.set_option("display.max_colwidth", 300)

amazon_pairs[["text_customer", "text_response"]].sample(10, random_state=42)

,text_customer,text_response
117216,Yo necesitaba elevar el espejo de mi tocador y encontré esta solución en @116928 que os parece?\n#Amazon https://t.co/0quPto0kx4,"@565800 Hola, Aranzazu. ¡Una solución inteligente y práctica! Espero que estés disfrutando de tu compra. :D ^CR https://t.co/fQfvAHx8nj"
119196,"@AmazonHelp Once You Receive..? I did't Send by Postal Mail. Its a Digital Form...Hope You could Get it Instantly!By the Way What is ^SQ, ^NR and ^SV ?",@367525 Sorry for the confusion. Request you to write back to the email you've received from our team and we (1/2)^SQ
107470,@AmazonHelp so I’ve had an issue and no one has responded to me 😐,@479947 We'd love to take a closer look into your order with you here: https://t.co/hApLpMlfHN ^QJ
71350,@AmazonHelp Thank you,"@366678 You are welcome, Akshay. ^AU"
34854,@137605 Ayer no me entregaron un paquete de @116928 por ausente a las 18:35. Pero si me entregan un certificado de @4496 a esa misma hora. Concerto 2°entrega hoy de 17 a 20 horas y aquí sigo esperando como un gilipollas. ES UNA PUTA VERGUENZA！ @135806,"@221198 Hola, lamentamos los inconvenientes que estás teniendo con tu entrega. Podrías indicarnos ¿cuál es la fecha de entrega que te indicamos en el correo electrónico de confirmación del pedido y si has logrado comunicarte con el transportista? ^MZ"
153061,@AmazonHelp please help me understand why I am unable to download @183790 book off my Amazon App? Was wanting to listen through @1016,@602543 I'm very sorry for any difficulties. What device are you using? Are you currently using the latest update for the app? Have you tried uninstalling and re-installing the app? Let us know more about the issue you're experiencing. We'd be happy to assist. ^SK
95196,"@AmazonHelp Just track order, return or replace, and view item details","@451690 The seller is in the best position to answer your question. To do that, go to the item page and click on their name. ^EM"
75565,"@AmazonHelp - Order No 407-6706063-7981118. God know when will you guys delivery. Terrible Service, no one knows the status.",@383173 Please don’t provide your order details as it is personal information. Our Twitter page is visible to the public. ^MS
21049,@AmazonHelp That takes me to the .com site. I think I need to go to .ca? My password isn’t working there.,@187800 That link will send your info to our Social Media team. Your password on the U.S. and Canadian sites will be the same. ^GR
159330,fiz comprinhas na amazon quinta e já recebi. @117086 te amo &lt;3,"@791495 Olá Analua! Que emoção!😱 Me diga, que você comprou?🙃 ^HC https://t.co/DWmfwnEgli"

In [38]:
amazon_pairs.head(10)

,tweet_id_response,author_id,inbound,created_at,text_response,response_tweet_id,in_response_to_tweet_id,tweet_id_customer,text_customer,customer_length,response_length
0,269,AmazonHelp,False,Wed Nov 22 09:23:01 +0000 2017,@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは、どのような状況でしょうか。一般的なトラブルシューティングを記載したヘルプがございますので、ご参照ください。https://t.co/2pbG55qJ7h ET,"270,271",272.0,272,amazonのfireTVstickが見れない😢,24,126
1,273,AmazonHelp,False,Wed Nov 22 09:40:27 +0000 2017,@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました。リプライいただきありがとうございました。ET,274,271.0,271,@AmazonHelp 電話で対応してもらいましたが改良されませんでした。\n保証期間も過ぎてるので買い直しになるんでしょうね。,63,69
2,275,AmazonHelp,False,Wed Nov 22 10:06:26 +0000 2017,@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお願いします。ET,NaN,274.0,274,@AmazonHelp こちらこそありがとうございました。,29,54
3,324,AmazonHelp,False,Wed Nov 22 09:06:00 +0000 2017,@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の再起動にて改善する場合がございますので、お試しください。改善しない場合は、状況を確認しご案内させていただきますのでこちらからカスタマーサービスまでご連絡ください。https://t.co/NtNAX2Qh2u ET,NaN,325.0,325,amazonプライムビデオ、再生エラーが多いです,24,153
4,615,AmazonHelp,False,Tue Oct 31 22:29:00 +0000 2017,"@115820 I'm sorry we've let you down! Without providing any personal information, will you describe the issue? We'd love to help. ^TN",616,617.0,617,Way to drop the ball on customer service @115821 so pissed right now!,69,133
5,618,AmazonHelp,False,Tue Oct 31 23:28:00 +0000 2017,@115820 We'd like to take a further look into this with you! Please reach us by phone or chat here: https://t.co/hApLpMlfHN ^AG,619,616.0,616,"@AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day",147,127
6,620,AmazonHelp,False,Tue Oct 31 22:28:34 +0000 2017,"@115822 I am unable to affect your account via Twitter. For real time support, phone or chat use this link: https://t.co/hApLpMlfHN ^CH",NaN,621.0,621,@115823 I want my amazon payments account CLOSED. dm me please.,64,135
7,622,AmazonHelp,False,Tue Oct 31 22:28:00 +0000 2017,"@115824 Hi, wir erhalten die Filme/Serien so vom jeweiligen Studio. Gebe ich aber direkt als Feedback dorthin weiter. Gruß ^JS",623,624.0,624,"@115825 also, beim Addams Family-Film in Prime sind Bild und Ton nicht wirklich synchron. Wie kommt's?",102,126
8,625,AmazonHelp,False,Tue Oct 31 22:34:32 +0000 2017,@115824 Wir haben zu danken. Schönen Abend noch. ^JS,NaN,623.0,623,"@AmazonHelp Okay, danke für die Info",36,52
9,626,AmazonHelp,False,Tue Oct 31 22:28:00 +0000 2017,@115826 I'm sorry for the wait. You'll receive an email as soon as we have an estimated delivery date. ^FJ,627,628.0,628,@115828 How about you guys figure out my Xbox One X project Scorpio edition first. No expected delivery or shipping date and it’s only a week away,146,106

In [ ]:
import re

def is_english(text):
    if not isinstance(text, str):
        return False
    return len(text.encode('ascii', 'ignore')) / (len(text) + 1e-5) > 0.85

clean_df = amazon_pairs[
    amazon_pairs['text_customer'].apply(is_english) & 
    amazon_pairs['text_response'].apply(is_english)
].copy()

def clean_tweet(text):
    text = re.sub(r'@[A-Za-z0-9_]+', '', str(text))
    text = re.sub(r'https?://\S+', '', text)
    text = re.sub(r'\^[A-Z0-9]+', '', text)
    return text.strip()

clean_df['clean_customer'] = clean_df['text_customer'].apply(clean_tweet)
clean_df['clean_response'] = clean_df['text_response'].apply(clean_tweet)

clean_df = clean_df[
    (clean_df['clean_customer'].str.len() > 15) & 
    (clean_df['clean_response'].str.len() > 15)
]

clean_df[['clean_customer', 'clean_response']].to_csv('amazon_pairs.csv', index=False)
print(f"Exported {len(clean_df)} clean English pairs to amazon_pairs.csv")

Exported 151058 clean English pairs to amazon_pairs.csv